-- Run in Supabase Dashboard → SQL Editor → New query

-- Signals (trading signals generated by admin Claude analysis)
create table if not exists signals (
  id                   uuid primary key default gen_random_uuid(),
  created_at           timestamptz default now(),
  session              text,
  focus                text,
  body_md              text not null,
  posted_telegram      boolean default false,
  posted_instagram     boolean default false
);

-- No RLS needed — signal visibility controlled by role checks in app code
