"use client";

import { useState } from "react";

interface Snapshot {
  id: string;
  created_at: string;
  session: string;
  focus: string;
  news_level: string;
  content?: string;
}

function formatDate(iso: string) {
  const d = new Date(iso);
  return d.toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short", year: "numeric" })
    + " · " + d.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
}

function focusLabel(f: string) {
  return f === "all" ? "All Markets" : f === "forex" ? "Forex" : "Crypto";
}

function newsColour(n: string) {
  return n === "major" ? "#ef4444" : n === "light" ? "#f59e0b" : "#22c55e";
}

function TerminalOutput({ text }: { text: string }) {
  return (
    <div style={{ fontFamily: "monospace", fontSize: 12, lineHeight: 1.8, whiteSpace: "pre-wrap", wordBreak: "break-word", color: "rgba(210,220,240,0.88)" }}>
      {text}
    </div>
  );
}

export default function SnapshotsClient({ initial }: { initial: Snapshot[] }) {
  const [snapshots, setSnapshots] = useState<Snapshot[]>(initial);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [content, setContent] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);

  async function expand(id: string) {
    if (expanded === id) { setExpanded(null); return; }
    setExpanded(id);
    if (content[id]) return;
    setLoading(id);
    const res = await fetch(`/api/admin/trading-snapshots?id=${id}`);
    if (res.ok) {
      const data = await res.json();
      setContent(prev => ({ ...prev, [id]: data.content }));
    }
    setLoading(null);
  }

  async function deleteSnapshot(id: string) {
    if (!confirm("Delete this snapshot?")) return;
    setDeleting(id);
    await fetch(`/api/admin/trading-snapshots?id=${id}`, { method: "DELETE" });
    setSnapshots(prev => prev.filter(s => s.id !== id));
    if (expanded === id) setExpanded(null);
    setDeleting(null);
  }

  return (
    <div style={{ padding: "40px 48px 80px", maxWidth: 1100 }}>
      <div style={{ fontSize: 10, letterSpacing: 3, textTransform: "uppercase", color: "#4f8ef7", marginBottom: 8 }}>Admin / Tools</div>
      <h1 style={{ fontFamily: "var(--font-syne), Syne, sans-serif", fontWeight: 800, fontSize: 36, letterSpacing: -1.5, marginBottom: 8 }}>
        Analysis Snapshots
      </h1>
      <p style={{ fontFamily: "monospace", fontSize: 12, color: "rgba(210,220,240,0.4)", marginBottom: 40 }}>
        {snapshots.length} saved · click a row to expand · generated by Trading Analysis tool
      </p>

      {snapshots.length === 0 ? (
        <div style={{ background: "#08090f", border: "1px solid rgba(255,255,255,0.04)", padding: "40px 24px", textAlign: "center" }}>
          <div style={{ fontFamily: "monospace", fontSize: 11, color: "rgba(210,220,240,0.2)" }}>
            {"// no snapshots yet — run an analysis and click \"save snapshot\""}
          </div>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
          {snapshots.map((s) => (
            <div key={s.id} style={{ background: "#08090f", border: "1px solid rgba(255,255,255,0.06)", borderLeft: expanded === s.id ? "2px solid #4f8ef7" : "2px solid rgba(255,255,255,0.06)" }}>
              {/* Row header */}
              <div
                onClick={() => expand(s.id)}
                style={{ padding: "12px 16px", display: "flex", alignItems: "center", gap: 12, cursor: "pointer" }}
              >
                <span style={{ fontFamily: "monospace", fontSize: 10, color: "rgba(79,142,247,0.5)", userSelect: "none" }}>
                  {expanded === s.id ? "▾" : "▸"}
                </span>
                <span style={{ fontFamily: "monospace", fontSize: 11, color: "rgba(210,220,240,0.7)", flex: 1 }}>
                  {formatDate(s.created_at)}
                </span>
                <span style={{ fontFamily: "monospace", fontSize: 10, letterSpacing: 1, color: "#4f8ef7", textTransform: "uppercase" }}>
                  {s.session}
                </span>
                <span style={{ fontFamily: "monospace", fontSize: 10, color: "rgba(210,220,240,0.4)", textTransform: "uppercase" }}>
                  {focusLabel(s.focus)}
                </span>
                <span style={{ fontFamily: "monospace", fontSize: 10, color: newsColour(s.news_level), textTransform: "uppercase" }}>
                  {s.news_level === "none" ? "no news" : s.news_level}
                </span>
                <button
                  onClick={(e) => { e.stopPropagation(); deleteSnapshot(s.id); }}
                  disabled={deleting === s.id}
                  style={{
                    fontFamily: "monospace", fontSize: 10, background: "none", cursor: "pointer",
                    color: "rgba(239,68,68,0.4)", border: "1px solid rgba(239,68,68,0.15)", padding: "2px 8px",
                  }}
                >
                  {deleting === s.id ? "..." : "delete"}
                </button>
              </div>

              {/* Expanded content */}
              {expanded === s.id && (
                <div style={{ borderTop: "1px solid rgba(255,255,255,0.04)", padding: "20px 24px 24px" }}>
                  {loading === s.id ? (
                    <div style={{ fontFamily: "monospace", fontSize: 12, color: "rgba(79,142,247,0.5)" }}>
                      <span style={{ animation: "pulse-dot 1.2s ease-in-out infinite", display: "inline-block" }}>●</span>
                      {" "}loading...
                    </div>
                  ) : content[s.id] ? (
                    <>
                      <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 12 }}>
                        <button
                          onClick={() => navigator.clipboard.writeText(content[s.id])}
                          style={{
                            fontFamily: "monospace", fontSize: 10, background: "none", cursor: "pointer",
                            color: "rgba(210,220,240,0.3)", border: "1px solid rgba(255,255,255,0.06)", padding: "3px 8px",
                          }}
                        >
                          copy
                        </button>
                      </div>
                      <TerminalOutput text={content[s.id]} />
                    </>
                  ) : (
                    <div style={{ fontFamily: "monospace", fontSize: 12, color: "rgba(239,68,68,0.5)" }}>failed to load</div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      <style>{`@keyframes pulse-dot { 0%,100%{opacity:1} 50%{opacity:0.3} }`}</style>
    </div>
  );
}
